name: hcp 
channels:
  - defaults
dependencies:
  - _r-mutex
  - asn1crypto
  - binutils_impl_linux-64
  - binutils_linux-64
  - boto
  - boto3
  - bwidget
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cryptography
  - curl
  - docutils
  - fontconfig
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - glib
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - icu
  - idna
  - jinja2
  - jmespath
  - jpeg
  - krb5
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - make
  - markupsafe
  - ncurses
  - openssl
  - pango
  - pcre
  - pip
  - pixman
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - python-dateutil
  - r-assertthat
  - r-base
  - r-bh
  - r-bindr
  - r-bindrcpp
  - r-bit
  - r-bit64
  - r-blob
  - r-cli
  - r-crayon
  - r-dbi
  - r-dbplyr
  - r-digest
  - r-dplyr
  - r-glue
  - r-magrittr
  - r-memoise
  - r-pillar
  - r-pkgconfig
  - r-plogr
  - r-prettyunits
  - r-purrr
  - r-r6
  - r-rcpp
  - r-rlang
  - r-rsqlite
  - r-tibble
  - r-tidyselect
  - r-utf8
  - readline
  - rpy2
  - setuptools
  - six
  - sqlite
  - tk
  - tktable
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - awscli
    - botocore
    - bz2file
    - colorama
    - nibabel
    - numpy
    - pyasn1
    - pyyaml
    - rsa
    - s3transfer

